import {PLAN} from './plan.js';
import {STORAGE_KEY,blankState,isoToday,shiftDate,formatDate,hours,escapeHTML as e,sectionScore,attempts,accuracy,totalScore,effectiveDay,progress,validateMock,validateState,mergeState,report} from './core.js';
import {strategyHTML,resourcesHTML} from './content.js';
let state=blankState(),storageOK=true,storageMessage='',toastTimer;
try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)state=validateState(JSON.parse(raw));}catch{storageOK=false;storageMessage='Saved data could not be read. Existing storage is untouched. New changes are temporary: export them before leaving.';}
const main=document.querySelector('#main'),dialog=document.querySelector('#mock-dialog'),form=document.querySelector('#mock-form');
const clampDate=d=>d<PLAN.startDate?PLAN.startDate:d>PLAN.examDate?PLAN.examDate:d;
let selected=clampDate(state.selectedDate||isoToday());
const byDate=d=>PLAN.days.find(x=>x.date===d);
function notify(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),4500);}
function save(){if(storageOK){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));document.querySelector('#save-status').textContent='Saved in this browser';}catch{storageOK=false;storageMessage='Browser storage is unavailable or full. Your changes are temporary. Export a backup before leaving.';notify(storageMessage);}}else document.querySelector('#save-status').textContent='Temporary session · export to keep';updateRail();}
function updateRail(){const p=progress(PLAN,state);document.querySelector('#rail-progress').style.width=p.percent+'%';document.querySelector('#rail-count').textContent=`${p.done} of ${p.total} tasks completed · ${p.percent}%`;}
const anchor=(url,text)=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${text} ↗</a>`;
const stat=(label,value,sub)=>`<div class="stat"><span class="label">${label}</span><strong>${value}</strong><small>${sub}</small></div>`;
const view=()=>['plan','mocks','strategy','resources'].includes(location.hash.slice(1))?location.hash.slice(1):'plan';
function dayCompleted(day){const tasks=effectiveDay(day,state,PLAN).tasks.filter(t=>!t.optional);return tasks.length>0&&tasks.every(t=>state.tasks[t.id]);}
function mobileBackup(){return `<div class="mobile-only"><button class="text-button" data-export>↓ Back up progress</button><button class="text-button" data-import>↑ Import backup</button><span class="hint">Saved in this browser · no cloud sync</span></div>`;}
function render(){document.querySelectorAll('[data-view]').forEach(a=>{const active=a.dataset.view===view();a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});main.innerHTML=(storageMessage?`<div class="banner">${e(storageMessage)}</div>`:'')+({plan:planHTML,mocks:mocksHTML,strategy:strategyHTML,resources:()=>resourcesHTML(PLAN.links)}[view()]())+mobileBackup();updateRail();if(view()==='strategy')updateCalculator();}
function planHTML(){
 const p=progress(PLAN,state),day=effectiveDay(byDate(selected),state,PLAN),today=isoToday();
 const daysLeft=Math.max(0,Math.ceil((new Date(PLAN.examDate+'T12:00Z')-new Date(today+'T12:00Z'))/86400000));
 const full=state.mocks.filter(m=>m.type==='full'),reviewed=full.filter(m=>m.reviewed);
 const index=PLAN.days.findIndex(d=>d.date===selected),start=Math.floor(index/7)*7,week=PLAN.days.slice(start,start+7);
 const completed=day.tasks.filter(t=>!t.optional&&state.tasks[t.id]).length,required=day.tasks.filter(t=>!t.optional).length;
 const next=PLAN.mocks.find(m=>!m.optional&&m.date>=selected),opt=PLAN.mocks.find(m=>m.id===day.optionalMock);
 return `<div class="page-heading"><div><span class="eyebrow">A LITTLE CLEARER, EVERY DAY</span><h1>Your next step, <em>mapped.</em></h1><p>A manageable start. Deliberate practice. Enough room to learn from every mock.</p></div><span class="pill">${daysLeft} days to CAT</span></div>
 <div class="hero"><div><span class="eyebrow">${e(day.phase.toUpperCase())}</span><h2>${e(day.kind==='break'?'Rest is part of the plan.':day.kind==='mock'?'A test is only half the work.':'Protect the session. Trust the process.')}</h2><p>${e(day.kind==='break'?'Your schedule already makes room for this break. Return to the next planned day without doubling the workload.':'Start with the first task below. Finish its review before adding more. Progress comes from understanding what changed.')}</p></div><div class="hero-stat"><strong>${hours(day.minutes)}</strong><span>PLANNED TODAY</span></div></div>
 <div class="stats">${stat('Plan completed',p.percent+'%',p.done+' / '+p.total+' required tasks')}${stat('Full mocks logged',full.length+' <span class="muted small">/ 12</span>','+2 optional, only when ready')}${stat('Mocks analysed',reviewed.length+' <span class="muted small">/ '+full.length+'</span>','Review is part of practice')}${stat('Work checked off',hours(p.minutes),'Planned duration, not a stopwatch')}</div>
 <div class="section-heading"><h2>Your week at a glance</h2><div class="controls"><button class="icon-button" data-week="-1" aria-label="Previous week" ${start===0?'disabled':''}>‹</button><span class="week-label">${formatDate(week[0].date,true)} – ${formatDate(week.at(-1).date,true)}</span><button class="icon-button" data-week="1" aria-label="Next week" ${start+7>=PLAN.days.length?'disabled':''}>›</button><button class="secondary" id="today">Today</button></div></div>
 <div class="week-grid">${week.map(d=>{const ed=effectiveDay(d,state,PLAN);return `<button class="day-button ${d.date===selected?'selected':''} ${d.date===today?'today':''} ${dayCompleted(d)?'done':''}" data-date="${d.date}" aria-pressed="${d.date===selected}" aria-label="${formatDate(d.date)}: ${e(ed.title)}"><span>${new Date(d.date+'T12:00Z').toLocaleDateString('en-IN',{weekday:'short'}).toUpperCase()}</span><strong>${Number(d.date.slice(-2))}</strong><small>${dayCompleted(d)?'✓ DONE':ed.kind==='mock'?'MOCK':ed.kind==='break'?'REST':hours(ed.minutes)}${ed.kind==='mock'?'<i></i>':''}</small></button>`;}).join('')}</div>
 <div class="day-layout"><section class="panel"><div class="section-heading"><div><h2 class="day-title">${e(day.title)}</h2><p class="date-caption">${formatDate(day.date)} · ${day.weekend?'Flexible weekend blocks':day.kind==='study'?'Start at 8:00 p.m.':'Follow the day’s blocks'} · ${hours(day.minutes)} + breaks</p></div><span class="pill ${day.kind==='mock'?'amber':'gray'}">${e(day.kind)}</span></div>
 ${day.note?`<p class="day-note">${e(day.note)}</p>`:''}
 ${opt?`<div class="optional-box"><label><input type="checkbox" data-optional="${opt.id}" ${state.optionalMocks[opt.id]?'checked':''}>Use optional ${e(opt.name)} instead of normal practice</label><p>Enable only when earlier reviews are finished and foundation work is on track. This also replaces tomorrow’s first block with analysis.</p></div>`:''}
 ${day.tasks.map(t=>`<article class="task ${state.tasks[t.id]?'completed':''}"><input class="task-check" id="${t.id}" type="checkbox" data-task="${t.id}" ${state.tasks[t.id]?'checked':''} aria-label="Complete ${e(t.title)}"><div><div class="task-meta ${t.section}">${e(t.section)}${t.optional?' · OPTIONAL':''}</div><h3 class="task-title">${e(t.title)}</h3><p>${e(t.detail)}</p>${anchor(t.url,t.section==='Mock'?'Open test':t.section==='Admin'||t.section==='Exam'?'Official instructions':'Open study material')}${t.section==='Mock'?` <button class="text-button" data-log-test="${PLAN.mocks.find(m=>m.date===day.date)?.id||''}">Log result →</button>`:''}</div><span class="task-time">${t.minutes} min</span></article>`).join('')}
 </section><aside class="side-stack"><section class="panel"><h3>Today’s progress</h3><div class="big-number">${completed}<span class="muted" style="font-size:20px"> / ${required}</span></div><div class="day-progress"><span style="width:${required?completed/required*100:0}%"></span></div><p>${required===0?'No required work today.':completed===required?'Session complete. Leave yourself one useful note.':'One task at a time. Review counts as work.'}</p></section><section class="panel"><label class="note-label" for="daily-note">One thing I learned today</label><textarea id="daily-note" rows="5" maxlength="6000" placeholder="What clicked? What needs a second attempt?">${e(state.notes[selected]||'')}</textarea><p class="hint">Saves as you type, in this browser.</p></section><section class="panel"><h3>${next?'Next planned mock':'Finish with confidence'}</h3>${next?`<p><strong>${e(next.name)}</strong><br>${formatDate(next.date)}</p><button class="secondary" data-date="${next.date}">See mock day ↗</button>`:'<p>Keep your strategy simple and familiar.</p>'}<a class="link-row" href="#strategy">Your attempt strategy <span>↗</span></a><a class="link-row" href="#mocks">Mock analysis checklist <span>↗</span></a></section></aside></div>
 <details style="margin-top:25px"><summary>See the complete 65-day calendar</summary><div class="calendar-all">${PLAN.days.map(d=>{const ed=effectiveDay(d,state,PLAN);return `<button class="${ed.kind} ${dayCompleted(d)?'complete':''}" data-date="${d.date}">${formatDate(d.date,true)}<small>${e(ed.kind==='mock'?ed.title:ed.kind==='break'?'Protected break':ed.phase)}</small></button>`;}).join('')}</div></details>`;
}
function chartHTML(records){
 const sorted=records.filter(m=>m.type==='full'&&m.unseen).sort((a,b)=>a.date.localeCompare(b.date));if(!sorted.length)return '';
 const w=620,h=200,pad=30,max=Math.max(60,...sorted.map(totalScore)),min=Math.min(0,...sorted.map(totalScore)),range=max-min||1;
 const x=i=>pad+(sorted.length===1?.5:i/(sorted.length-1))*(w-2*pad),y=n=>h-pad-(n-min)/range*(h-2*pad);
 return `<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="Raw scores for unseen full mocks, ordered by test date. Different tests can have different difficulty.">${[0,.5,1].map(f=>{const n=min+range*f;return `<line class="gridline" x1="${pad}" x2="${w-pad}" y1="${y(n)}" y2="${y(n)}"/><text x="0" y="${y(n)+3}">${Math.round(n)}</text>`;}).join('')}<polyline points="${sorted.map((m,i)=>`${x(i)},${y(totalScore(m))}`).join(' ')}"/>${sorted.map((m,i)=>`<circle cx="${x(i)}" cy="${y(totalScore(m))}" r="5"><title>${e(m.name)}: ${totalScore(m)} raw</title></circle><text x="${x(i)}" y="${y(totalScore(m))-12}" text-anchor="middle">${totalScore(m)}</text>${i===0||i===sorted.length-1?`<text x="${x(i)}" y="${h-6}" text-anchor="middle">${formatDate(m.date,true)}</text>`:''}`).join('')}</svg>`;
}
function mocksHTML(){
 const full=state.mocks.filter(m=>m.type==='full'),unseen=full.filter(m=>m.unseen).sort((a,b)=>a.date.localeCompare(b.date)),last=unseen.slice(-3),avg=last.length?(last.reduce((s,m)=>s+totalScore(m),0)/last.length).toFixed(1):'—',pending=full.filter(m=>!m.reviewed).length;
 return `<div class="page-heading"><div><span class="eyebrow">PRACTICE. DIAGNOSE. REATTEMPT.</span><h1>The mock <em>lab.</em></h1><p>12 full mocks, 2 optional, 8 sectionals. Every test comes with time to understand it.</p></div><button class="primary" id="new-mock">+ Log a result</button></div>
 <div class="stats">${stat('Full mocks',full.length,'12 planned + 2 optional')}${stat('Last 3 unseen · avg',avg,'Raw marks · mixed difficulty')}${stat('Analysis waiting',pending,'Full mocks not marked reviewed')}${stat('Analysis logged',hours(state.mocks.reduce((s,m)=>s+m.analysisMinutes,0)),'Minutes entered by you')}</div>
 ${pending>=2?'<div class="banner">Two or more full mocks await review. Finish those before enabling an optional mock. More tests alone will not repair the same errors.</div>':''}
 <div class="mock-layout"><div><section class="panel"><div class="section-heading"><h2>Your score journal</h2><button class="secondary" id="copy-report">Copy review summary ↗</button></div>${state.mocks.length?chartHTML(state.mocks)+`<p class="hint">Unseen full-test raw scores only. Difficulty varies; the line is not a CAT percentile forecast.</p>${state.mocks.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(m=>`<article class="mock-entry"><div><strong>${e(m.name)}</strong><p>${formatDate(m.date)} · ${m.unseen?'Unseen':'Previously seen'} · ${m.type} · ${m.reviewed?'Analysis complete':'Analysis pending'}</p><div class="scores-row">${Object.entries(m.sections).map(([k,s])=>`<span>${k} <b>${sectionScore(s)}</b> · ${accuracy(s)??'—'}% acc.</span>`).join('')}</div>${m.notes?`<p>${e(m.notes.slice(0,180))}${m.notes.length>180?'…':''}</p>`:''}</div><div class="result-actions"><span class="score-badge">${totalScore(m)}</span><button class="secondary" data-edit="${e(m.id)}">Edit</button></div></article>`).join('')}`:`<div class="empty-state"><strong>Your baseline starts here.</strong><p>Take the first unseen mock. Enter correct, wrong MCQ and wrong TITA counts for each section. A low first score gives us a starting point.</p><button class="primary" data-log-test="mock-09-27">Log the first mock ↗</button></div>`}</section>
 <section class="panel" style="margin-top:24px"><h2>The review that improves the next test</h2><ol class="analysis-list"><li><strong>First 15 minutes:</strong> capture section scores, attempts, accuracy, time lost and first impressions.</li><li><strong>Next 60–90:</strong> retry accessible wrong and skipped questions without solutions. Explain what blocked you.</li><li><strong>Next 45–60:</strong> study explanations. Check lucky correct answers and compare your selected sets/passages with better choices.</li><li><strong>Final 15:</strong> record three changes and queue selected errors for +2-day and +7-day reattempts in the daily review blocks.</li></ol><p class="small muted">Budget about 2½–3 hours per full-test review. Split it across the mock day and next day. The analysis-complete flag is separate from finishing the test.</p></section></div>
 <section class="panel"><div class="section-heading"><h2>Your test calendar</h2><span class="pill gray">Before 23 Nov</span></div><p class="hint">Use a different unseen paper if you have studied a scheduled one. Log the actual name.</p><div class="schedule-list">${[...PLAN.mocks,...PLAN.sectionals].sort((a,b)=>a.date.localeCompare(b.date)).map(m=>`<div class="schedule-item"><time>${formatDate(m.date,true)}</time><div><strong>${e(m.name)}</strong><span>${m.optional?'Optional · replaces study':m.type==='full'?'120 min + analysis':'40 min + review'}</span>${m.optional?'<b class="tag">Only after review is complete</b>':''}</div><button class="secondary" data-log-test="${m.id}">Log</button></div>`).join('')}</div></section></div>`;
}
function changeDate(date){selected=clampDate(date);state.selectedDate=selected;save();if(view()!=='plan')location.hash='plan';else render();}
function download(text,name,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportProgress(){download(JSON.stringify({...state,exportedAt:new Date().toISOString(),planVersion:PLAN.version},null,2),'cat-compass-backup-'+isoToday()+'.json');notify('Backup exported. Keep it before switching devices.');}
async function copyReport(){const text=report(state,PLAN);try{await navigator.clipboard.writeText(text);notify('Review summary copied. Paste it into our chat.');}catch{download(text,'cat-review-'+isoToday()+'.txt','text/plain');notify('Clipboard unavailable. Review summary downloaded instead.');}}
function renderScoreFields(values){const sectionKeys=form.elements.type.value==='full'?['VARC','DILR','QA']:[form.elements.section.value];document.querySelector('#section-choice').classList.toggle('hidden',form.elements.type.value==='full');document.querySelector('#score-inputs').innerHTML=sectionKeys.map(k=>`<div class="answer-grid"><strong>${k}</strong>${[['correct','Correct'],['wrongMCQ','Wrong MCQ'],['wrongTITA','Wrong TITA']].map(([field,label])=>`<label>${label}<input aria-label="${k} ${label}" name="${k}-${field}" type="number" min="0" max="${k==='VARC'?24:22}" step="1" value="${values?.[k]?.[field]??0}" required></label>`).join('')}</div>`).join('');previewScore();}
function readSections(){const keys=form.elements.type.value==='full'?['VARC','DILR','QA']:[form.elements.section.value];return Object.fromEntries(keys.map(k=>[k,Object.fromEntries(['correct','wrongMCQ','wrongTITA'].map(f=>[f,Number(form.elements[k+'-'+f].value)]))]));}
function previewScore(){const sections=readSections();document.querySelector('#score-preview').textContent=Object.entries(sections).map(([k,s])=>`${k}: ${sectionScore(s)} raw`).join(' · ')+' | Total: '+Object.values(sections).reduce((a,s)=>a+sectionScore(s),0);}
function openMock(id,editing=false){
 let m=editing?state.mocks.find(m=>m.id===id):[...PLAN.mocks,...PLAN.sectionals].find(m=>m.id===id);
 if(!editing&&m){const existing=state.mocks.find(x=>x.name===m.name&&x.date===m.date&&x.type===m.type);if(existing){m=existing;editing=true;}}
 form.reset();form.elements.id.value=editing?m.id:'';form.elements.name.value=m?.name||'';form.elements.date.value=m?.date||isoToday();form.elements.type.value=m?.type||'full';form.elements.section.value=m?.section||(m?.sections?Object.keys(m.sections)[0]:'VARC');form.elements.analysisMinutes.value=editing?m.analysisMinutes:0;form.elements.unseen.checked=editing?m.unseen:true;form.elements.reviewed.checked=editing?m.reviewed:false;form.elements.notes.value=editing?m.notes:'';
 document.querySelector('#dialog-title').textContent=editing?'Update your result':'Log your mock';document.querySelector('#delete-mock').hidden=!editing;document.querySelector('#form-error').textContent='';renderScoreFields(editing?m.sections:null);dialog.showModal();
}
function updateCalculator(){const vals=['calc-c','calc-w','calc-t'].map(id=>Number(document.getElementById(id)?.value));const box=document.querySelector('#calc-result');if(!box)return;if(vals.some(v=>!Number.isInteger(v)||v<0)||vals.reduce((a,b)=>a+b,0)>24){box.textContent='Use non-negative whole counts, up to 24 attempted questions in this illustration.';return;}const s={correct:vals[0],wrongMCQ:vals[1],wrongTITA:vals[2]};box.innerHTML=`<strong>${sectionScore(s)}</strong><span>raw marks<br><span class="small muted">${attempts(s)} attempts · ${accuracy(s)??'—'}% accuracy</span></span>`;}
document.addEventListener('click',ev=>{
 const b=ev.target.closest('button');if(!b)return;
 if(b.dataset.date){changeDate(b.dataset.date);return;}
 if(b.dataset.week){changeDate(shiftDate(selected,Number(b.dataset.week)*7));return;}
 if(b.id==='today'){changeDate(isoToday());return;}
 if(b.id==='new-mock'){openMock();return;}
 if(b.dataset.logTest){openMock(b.dataset.logTest);return;}
 if(b.dataset.edit){openMock(b.dataset.edit,true);return;}
 if(b.id==='close-dialog'){dialog.close();return;}
 if(b.id==='export'||b.hasAttribute('data-export')){exportProgress();return;}
 if(b.hasAttribute('data-import')){document.querySelector('#import').click();return;}
 if(b.id==='copy-report'){copyReport();return;}
 if(b.id==='delete-mock'){
  const id=form.elements.id.value,removed=state.mocks.find(m=>m.id===id);if(!removed)return;state.mocks=state.mocks.filter(m=>m.id!==id);save();dialog.close();render();notify('Result deleted. Use Undo to restore.');
  const t=document.querySelector('#toast'),undo=document.createElement('button');undo.textContent='Undo';undo.className='secondary';undo.style.marginLeft='12px';undo.addEventListener('click',()=>{state.mocks.push(removed);save();render();notify('Result restored.');});t.append(undo);clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),15000);
 }
});
document.addEventListener('change',ev=>{
 const t=ev.target;
 if(t.dataset.task){state.tasks[t.dataset.task]=t.checked;save();render();document.getElementById(t.id)?.focus();}
 if(t.dataset.optional){state.optionalMocks[t.dataset.optional]=t.checked;save();render();}
 if(t===form.elements.type||t===form.elements.section)renderScoreFields();
});
document.addEventListener('input',ev=>{
 if(ev.target.id==='daily-note'){state.notes[selected]=ev.target.value;save();}
 if(ev.target.id.startsWith('calc-'))updateCalculator();
 if(ev.target.closest('#score-inputs'))previewScore();
});
form.addEventListener('submit',ev=>{ev.preventDefault();try{
 const m=validateMock({id:form.elements.id.value||crypto.randomUUID(),name:form.elements.name.value,date:form.elements.date.value,type:form.elements.type.value,sections:readSections(),analysisMinutes:Number(form.elements.analysisMinutes.value),unseen:form.elements.unseen.checked,reviewed:form.elements.reviewed.checked,notes:form.elements.notes.value,updatedAt:new Date().toISOString()});
 if(/2023/.test(m.name)&&m.sections.DILR&&attempts(m.sections.DILR)>20)throw Error('CAT 2023 DILR had 20 questions; check the answer counts.');
 if(m.reviewed&&m.analysisMinutes===0)throw Error('Add your analysis time before marking the review complete.');
 const i=state.mocks.findIndex(x=>x.id===m.id);if(i<0)state.mocks.push(m);else state.mocks[i]=m;save();dialog.close();if(view()!=='mocks')location.hash='mocks';else render();notify('Result saved. Use the review summary when updating the plan.');
 }catch(err){document.querySelector('#form-error').textContent=err.message;}});
document.querySelector('#import').addEventListener('change',async ev=>{const f=ev.target.files[0];if(!f)return;try{if(f.size>2_000_000)throw Error('Backup is too large (maximum 2 MB).');const incoming=validateState(JSON.parse(await f.text()));state=mergeState(state,incoming);save();render();notify('Backup merged. Existing mock results are preserved; matching progress uses imported values.');}catch(err){notify('Import failed: '+err.message);}finally{ev.target.value='';}});
window.addEventListener('hashchange',()=>{render();window.scrollTo({top:0,behavior:'instant'});});
window.addEventListener('storage',ev=>{if(ev.key===STORAGE_KEY&&ev.newValue){try{state=validateState(JSON.parse(ev.newValue));if(!dialog.open)render();}catch{notify('Another tab wrote unreadable data. Export your current progress.');}}});
render();
